{% set name = "fastapi" %}
{% set version = "0.109.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5402389843a3561918634eb327e86b9ae98645a9e7696bede9074449c48d610a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.13.0
  run:
    - anyio >=3.7.1,<4.0.0
    - python >=3.8
    - starlette >=0.35.0,<0.36.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0
    - typing-extensions >=4.8.0

test:
  imports:
    - fastapi
    - fastapi.dependencies
    - fastapi.middleware
    - fastapi.openapi
    - fastapi.security

about:
  home: https://github.com/tiangolo/fastapi
  license: MIT
  license_file: LICENSE
  summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
  doc_url: https://github.com/tiangolo/fastapi
  dev_url: https://github.com/tiangolo/fastapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - tiangolo
    - synapticarbors
